import type { CSSProperties } from "react";
import type { Metadata } from "next";
import { Roboto, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SidebarInset, SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar"
import { AppSidebar } from "@/app/mycomponents/app-sidebar"
import Header  from "@/app/mycomponents/header"
import Providers from "@/app/providers"

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  variable: "--font-sans",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Route Cinema",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${roboto.variable} ${geistMono.variable} dark h-full antialiased`}
      suppressHydrationWarning
    >
      <body
        className="min-h-full flex flex-col bg-slate-950 text-slate-100 has-header" 
        style={{ "--header-height": "4rem" } as CSSProperties}
      >
        <Providers>
          <Header />
          <SidebarProvider
            className="flex-1"
            style={{ paddingTop: "var(--header-height)" } as CSSProperties}
          >
            <AppSidebar />
            <SidebarInset>
              <SidebarTrigger />
              {children}
            </SidebarInset>
          </SidebarProvider>
        </Providers>
      </body>
    </html>
  );
}